feat- React: Basic Route Setup and Layout #40989
Priyankatiyar/javascript_Client pull request #11
Opened 2020-12-21 13:24 UTC by Priyankatiyar

Create a new feature branch 40989.
[Refer Task](https://redmine.successive.tech/issues/40989)
![NotFoundRoute](https://user-images.githubusercontent.com/73167663/102781551-dec0f680-43bd-11eb-8da8-a22f8f75ef0d.PNG)
![childrRout](https://user-images.githubusercontent.com/73167663/102781556-dff22380-43bd-11eb-8b68-01d3485be052.PNG)
![inputRout](https://user-images.githubusercontent.com/73167663/102781559-e08aba00-43bd-11eb-91c8-18543a29b385.PNG)
![textFielRout](https://user-images.githubusercontent.com/73167663/102781561-e1235080-43bd-11eb-93db-3073a6a01699.PNG)
![traineeRout](https://user-images.githubusercontent.com/73167663/102781562-e1bbe700-43bd-11eb-84fa-e6a9ce892e4e.PNG)
![d-11LOgin](https://user-images.githubusercontent.com/73167663/102781563-e1bbe700-43bd-11eb-9b8e-1cba75902ae2.PNG)

2020-12-21 13:35 UTC, shashank-nx requested changes

2020-12-21 13:35 UTC, shashank-nx commented on training/src/pages/ChildrenDemo/ChildrenDemo.jsx
> +import NavBar from '../../layouts/components/Navbar/Navbar';
Change` NavBar` Path with `'../../layouts/components/Navbar/'`

2020-12-21 13:35 UTC, shashank-nx commented on training/src/pages/InputDemo/InputDemo.jsx
> +import NavBar from '../../layouts/components/Navbar/Navbar';
Change `NavBar` Path with `'../../layouts/components/Navbar/'`

2020-12-21 13:35 UTC, shashank-nx commented on training/src/pages/Login/Login.jsx
> +import Footer from '../../layouts/components/Footer/Footer';
Change `Footer` Path with `'../../layouts/components/Footer/'`

2020-12-21 13:35 UTC, shashank-nx commented on training/src/pages/NoMatch/NoMatch.jsx
> +import NavBar from '../../layouts/components/Navbar/Navbar';
Change `NavBar` Path with `'../../layouts/components/Navbar/'`

2020-12-21 13:35 UTC, shashank-nx commented on training/src/pages/TextFieldDemo/TextFieldDemo.jsx
> +import NavBar from '../../layouts/components/Navbar/Navbar';
Change `NavBar` Path with `'../../layouts/components/Navbar/'`

2020-12-21 13:35 UTC, shashank-nx commented on training/src/pages/Trainee/Trainee.jsx
> +import NavBar from '../../layouts/components/Navbar/Navbar';
Change `NavBar` Path with `'../../layouts/components/Navbar/'`

2020-12-21 13:35 UTC, shashank-nx commented on training/src/routes/AuthRoute.jsx
> +import AuthLayout from '../layouts/AuthLayout/AuthLayout';
Change `AuthLayout` Path with `'../layouts/AuthLayout/AuthLayout'`

2020-12-21 13:35 UTC, shashank-nx commented on training/src/routes/PrivateRoute.jsx
> +import { PrivateLayout } from '../layouts/index';
import { PrivateLayout } from '../layouts/index'; No need to pass index here.

2020-12-22 10:22 UTC, Priyankatiyar commented on training/src/pages/ChildrenDemo/ChildrenDemo.jsx
> +import NavBar from '../../layouts/components/Navbar/Navbar';
Done.

2020-12-22 10:30 UTC, shashank-nx approved these changes
Looks fine to me.

2020-12-22 10:31 UTC, merged